### PR TITLE
so good at copying code

### PR DESCRIPTION
**Pull request by webdev03**
thanks MDN!

### CODE REVIEW

**Comment by Chiroyce1** [comment]
merge go brrr..

**Comment by webdev03** [comment]
squash and merge go: u guys forgot about me 😭

**Comment by Chiroyce1** [comment]
tbh i didnt check if this method is faster.. do you think it is?

**Comment by webdev03** [comment]
squash and merge combines all the commits into one

this is faster since u dont need to connect to the network and backend stuff, you could make this a PWA lol

**Comment by Chiroyce1** [comment]
how do i squash and merge?

**Comment by webdev03** [comment]
where the green button to merge a PR, there is a dropdown, you can also rebase the PR or squash and merge it there. i think rebasing recreates the commits

**Pull request merged**
